site_name: Корректум
site_url: https://correctum.github.io/
site_author: ООО "АТС"

repo_name: correctum/docs
repo_url: https://github.com/correctum/correctum.github.io
edit_uri: edit/dev/docs/

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  language: ru
  logo: https://avatars.githubusercontent.com/u/261857966
  favicon: https://avatars.githubusercontent.com/u/261857966
  features:
    - content.action.edit
    - content.action.view
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.suggest

plugins:
  - glightbox:
      touchNavigation: true
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto

nav:
  - index.md
  - Импортеры:
    - OFD.ru: importers/ofdru.md
