site_name: Correctum
site_url: https://correctum.github.io/
site_author: ornaras

repo_name: correctum/docs
repo_url: https://github.com/correctum/correctum.github.io
edit_uri: edit/dev/docs/

theme:
  name: material
  logo: https://avatars.githubusercontent.com/u/261857966
  features:
    - content.action.edit
    - content.action.view
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.suggest

plugins:
  - glightbox:
      touchNavigation: true
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto

nav:
  - Импортеры:
    - OFD.ru: importers/ofdru.md